name: ci

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: tty-pt/ci/.github/workflows/all-in-one.yml@main
    with:
      name: libqmap
      deps: "libqsys,libxxhash-dev"
      deps_apk: "libqsys,xxhash-dev,libbsd-dev"
      deps_pacman: "libqsys,xxhash"
      deps_rpm: "libqsys,xxhash-devel"
      deps_brew: "libqsys,xxhash"
    secrets:
      HOST: ${{ secrets.OPENBSD_HOST }}
      USER: ${{ secrets.OPENBSD_USER }}
      SSH_KEY: ${{ secrets.OPENBSD_SSH_KEY }}
      GPG_PRIVATE_KEY: ${{ secrets.OPENBSD_GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.OPENBSD_GPG_PASSPHRASE }}
      GPG_KEYID: ${{ secrets.OPENBSD_GPG_KEY_ID }}
      ABUILD_PRIVATE_KEY: ${{ secrets.ABUILD_PRIVATE_KEY }}
      ABUILD_PUBLIC_KEY: ${{ secrets.ABUILD_PUBLIC_KEY }}
      TAP_TOKEN: ${{ secrets.TAP_TOKEN }}
